/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.analysis;

import org.peano.pdt.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseADescription(ADescription node);
    void caseARepository(ARepository node);
    void caseAVertex(AVertex node);
    void caseAReadScalarOperation(AReadScalarOperation node);
    void caseAReadVectorOperation(AReadVectorOperation node);
    void caseAReadVectorTwoPowDOperation(AReadVectorTwoPowDOperation node);
    void caseAReadStencilOperation(AReadStencilOperation node);
    void caseAReadIntergridOperatorOperation(AReadIntergridOperatorOperation node);
    void caseAWriteScalarOperation(AWriteScalarOperation node);
    void caseAWriteVectorOperation(AWriteVectorOperation node);
    void caseAWriteVectorTwoPowDOperation(AWriteVectorTwoPowDOperation node);
    void caseAWriteStencilOperation(AWriteStencilOperation node);
    void caseAWriteIntergridOperatorOperation(AWriteIntergridOperatorOperation node);
    void caseACell(ACell node);
    void caseAState(AState node);
    void caseAEventMapping(AEventMapping node);
    void caseAAdapter(AAdapter node);
    void caseAPredefinedAdapter(APredefinedAdapter node);

    void caseTTokenVertex(TTokenVertex node);
    void caseTTokenCell(TTokenCell node);
    void caseTTokenState(TTokenState node);
    void caseTTokenComponent(TTokenComponent node);
    void caseTTokenNamespace(TTokenNamespace node);
    void caseTTokenRead(TTokenRead node);
    void caseTTokenWrite(TTokenWrite node);
    void caseTTokenScalar(TTokenScalar node);
    void caseTTokenVectorD(TTokenVectorD node);
    void caseTTokenVectorTwoPowD(TTokenVectorTwoPowD node);
    void caseTTokenVectorFivePowD(TTokenVectorFivePowD node);
    void caseTTokenStencil(TTokenStencil node);
    void caseTTokenName(TTokenName node);
    void caseTTokenDastgenFile(TTokenDastgenFile node);
    void caseTTokenEventMapping(TTokenEventMapping node);
    void caseTTokenOpenBracket(TTokenOpenBracket node);
    void caseTTokenCloseBracket(TTokenCloseBracket node);
    void caseTTokenComma(TTokenComma node);
    void caseTTokenAdapter(TTokenAdapter node);
    void caseTTokenMergeWithUserDefinedAdapter(TTokenMergeWithUserDefinedAdapter node);
    void caseTTokenMergeWithPredefinedAdapter(TTokenMergeWithPredefinedAdapter node);
    void caseTBlank(TBlank node);
    void caseTIdentifier(TIdentifier node);
    void caseTFilename(TFilename node);
    void caseTNamespace(TNamespace node);
    void caseTTraditionalComment(TTraditionalComment node);
    void caseTDocumentationComment(TDocumentationComment node);
    void caseTEndOfLineComment(TEndOfLineComment node);
    void caseEOF(EOF node);
}
