/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.peano.pdt.node;

import de.tum.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenRepository extends Token
{
    public TTokenRepository()
    {
        super.setText("repository:");
    }

    public TTokenRepository(int line, int pos)
    {
        super.setText("repository:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenRepository(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenRepository(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenRepository text.");
    }
}
