/* This file was generated by SableCC (http://www.sablecc.org/). */

package de.tum.peano.pdt.node;

import de.tum.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorTwoPowD extends Token
{
    public TTokenVectorTwoPowD()
    {
        super.setText("vector2PowD:");
    }

    public TTokenVectorTwoPowD(int line, int pos)
    {
        super.setText("vector2PowD:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorTwoPowD(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorTwoPowD(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorTwoPowD text.");
    }
}
