/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.parser;

import org.peano.pdt.lexer.*;
import org.peano.pdt.node.*;
import org.peano.pdt.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AAdescription1Description */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AAdescription2Description */
		    {
			ArrayList list = new1();
			push(goTo(0), list);
		    }
		    break;
                    case 2: /* reduce AAdescription3Description */
		    {
			ArrayList list = new2();
			push(goTo(0), list);
		    }
		    break;
                    case 3: /* reduce AAdescription4Description */
		    {
			ArrayList list = new3();
			push(goTo(0), list);
		    }
		    break;
                    case 4: /* reduce AAvertex1Vertex */
		    {
			ArrayList list = new4();
			push(goTo(1), list);
		    }
		    break;
                    case 5: /* reduce AAvertex2Vertex */
		    {
			ArrayList list = new5();
			push(goTo(1), list);
		    }
		    break;
                    case 6: /* reduce AState */
		    {
			ArrayList list = new6();
			push(goTo(2), list);
		    }
		    break;
                    case 7: /* reduce ACell */
		    {
			ArrayList list = new7();
			push(goTo(3), list);
		    }
		    break;
                    case 8: /* reduce ASingleReadScalarOperationList */
		    {
			ArrayList list = new8();
			push(goTo(4), list);
		    }
		    break;
                    case 9: /* reduce AListReadScalarOperationList */
		    {
			ArrayList list = new9();
			push(goTo(4), list);
		    }
		    break;
                    case 10: /* reduce ASingleReadVectorOperationList */
		    {
			ArrayList list = new10();
			push(goTo(4), list);
		    }
		    break;
                    case 11: /* reduce AListReadVectorOperationList */
		    {
			ArrayList list = new11();
			push(goTo(4), list);
		    }
		    break;
                    case 12: /* reduce ASingleReadTokenVectorTwoPowDOperationList */
		    {
			ArrayList list = new12();
			push(goTo(4), list);
		    }
		    break;
                    case 13: /* reduce AListReadTokenVectorTwoPowDOperationList */
		    {
			ArrayList list = new13();
			push(goTo(4), list);
		    }
		    break;
                    case 14: /* reduce ASingleReadStencilOperationList */
		    {
			ArrayList list = new14();
			push(goTo(4), list);
		    }
		    break;
                    case 15: /* reduce AListReadStencilOperationList */
		    {
			ArrayList list = new15();
			push(goTo(4), list);
		    }
		    break;
                    case 16: /* reduce ASingleWriteScalarOperationList */
		    {
			ArrayList list = new16();
			push(goTo(4), list);
		    }
		    break;
                    case 17: /* reduce AListWriteScalarOperationList */
		    {
			ArrayList list = new17();
			push(goTo(4), list);
		    }
		    break;
                    case 18: /* reduce ASingleWriteVectorTwoPowDOperationList */
		    {
			ArrayList list = new18();
			push(goTo(4), list);
		    }
		    break;
                    case 19: /* reduce AListWriteVectorTwoPowDOperationList */
		    {
			ArrayList list = new19();
			push(goTo(4), list);
		    }
		    break;
                    case 20: /* reduce ASingleWriteVectorOperationList */
		    {
			ArrayList list = new20();
			push(goTo(4), list);
		    }
		    break;
                    case 21: /* reduce AListWriteVectorOperationList */
		    {
			ArrayList list = new21();
			push(goTo(4), list);
		    }
		    break;
                    case 22: /* reduce ASingleWriteStencilOperationList */
		    {
			ArrayList list = new22();
			push(goTo(4), list);
		    }
		    break;
                    case 23: /* reduce AListWriteStencilOperationList */
		    {
			ArrayList list = new23();
			push(goTo(4), list);
		    }
		    break;
                    case 24: /* reduce ASingleEventMappingList */
		    {
			ArrayList list = new24();
			push(goTo(5), list);
		    }
		    break;
                    case 25: /* reduce AListEventMappingList */
		    {
			ArrayList list = new25();
			push(goTo(5), list);
		    }
		    break;
                    case 26: /* reduce AAsingleadapterlist1AdapterList */
		    {
			ArrayList list = new26();
			push(goTo(6), list);
		    }
		    break;
                    case 27: /* reduce AAsingleadapterlist2AdapterList */
		    {
			ArrayList list = new27();
			push(goTo(6), list);
		    }
		    break;
                    case 28: /* reduce AAsingleadapterlist3AdapterList */
		    {
			ArrayList list = new28();
			push(goTo(6), list);
		    }
		    break;
                    case 29: /* reduce AAsingleadapterlist4AdapterList */
		    {
			ArrayList list = new29();
			push(goTo(6), list);
		    }
		    break;
                    case 30: /* reduce AAlistadapterlist1AdapterList */
		    {
			ArrayList list = new30();
			push(goTo(6), list);
		    }
		    break;
                    case 31: /* reduce AAlistadapterlist2AdapterList */
		    {
			ArrayList list = new31();
			push(goTo(6), list);
		    }
		    break;
                    case 32: /* reduce AAlistadapterlist3AdapterList */
		    {
			ArrayList list = new32();
			push(goTo(6), list);
		    }
		    break;
                    case 33: /* reduce AAlistadapterlist4AdapterList */
		    {
			ArrayList list = new33();
			push(goTo(6), list);
		    }
		    break;
                    case 34: /* reduce ASingleMergeWithUserDefinedAdapterList */
		    {
			ArrayList list = new34();
			push(goTo(7), list);
		    }
		    break;
                    case 35: /* reduce AListMergeWithUserDefinedAdapterList */
		    {
			ArrayList list = new35();
			push(goTo(7), list);
		    }
		    break;
                    case 36: /* reduce ASingleMergeWithPredefinedAdapterList */
		    {
			ArrayList list = new36();
			push(goTo(8), list);
		    }
		    break;
                    case 37: /* reduce AListMergeWithPredefinedAdapterList */
		    {
			ArrayList list = new37();
			push(goTo(8), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PDescription node1 = (PDescription) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AAdescription1Description */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDescription pdescriptionNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TNamespace tnamespaceNode3;
        PVertex pvertexNode4;
        PCell pcellNode5;
        PState pstateNode6;
        LinkedList listNode7 = new LinkedList();
        LinkedList listNode8 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        tnamespaceNode3 = (TNamespace)nodeArrayList4.get(0);
        pvertexNode4 = (PVertex)nodeArrayList5.get(0);
        pcellNode5 = (PCell)nodeArrayList6.get(0);
        pstateNode6 = (PState)nodeArrayList7.get(0);
        {
            // Block
        }
        {
            // Block
        }

        pdescriptionNode1 = new ADescription(tidentifierNode2, tnamespaceNode3, pvertexNode4, pcellNode5, pstateNode6, listNode7, listNode8);
        }
	nodeList.add(pdescriptionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AAdescription2Description */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDescription pdescriptionNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TNamespace tnamespaceNode3;
        PVertex pvertexNode4;
        PCell pcellNode5;
        PState pstateNode6;
        LinkedList listNode8 = new LinkedList();
        LinkedList listNode9 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        tnamespaceNode3 = (TNamespace)nodeArrayList4.get(0);
        pvertexNode4 = (PVertex)nodeArrayList5.get(0);
        pcellNode5 = (PCell)nodeArrayList6.get(0);
        pstateNode6 = (PState)nodeArrayList7.get(0);
        {
            // Block
        LinkedList listNode7 = new LinkedList();
        listNode7 = (LinkedList)nodeArrayList8.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        {
            // Block
        }

        pdescriptionNode1 = new ADescription(tidentifierNode2, tnamespaceNode3, pvertexNode4, pcellNode5, pstateNode6, listNode8, listNode9);
        }
	nodeList.add(pdescriptionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AAdescription3Description */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDescription pdescriptionNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TNamespace tnamespaceNode3;
        PVertex pvertexNode4;
        PCell pcellNode5;
        PState pstateNode6;
        LinkedList listNode7 = new LinkedList();
        LinkedList listNode9 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        tnamespaceNode3 = (TNamespace)nodeArrayList4.get(0);
        pvertexNode4 = (PVertex)nodeArrayList5.get(0);
        pcellNode5 = (PCell)nodeArrayList6.get(0);
        pstateNode6 = (PState)nodeArrayList7.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode8 = new LinkedList();
        listNode8 = (LinkedList)nodeArrayList8.get(0);
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }

        pdescriptionNode1 = new ADescription(tidentifierNode2, tnamespaceNode3, pvertexNode4, pcellNode5, pstateNode6, listNode7, listNode9);
        }
	nodeList.add(pdescriptionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AAdescription4Description */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PDescription pdescriptionNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TNamespace tnamespaceNode3;
        PVertex pvertexNode4;
        PCell pcellNode5;
        PState pstateNode6;
        LinkedList listNode8 = new LinkedList();
        LinkedList listNode10 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList2.get(0);
        tnamespaceNode3 = (TNamespace)nodeArrayList4.get(0);
        pvertexNode4 = (PVertex)nodeArrayList5.get(0);
        pcellNode5 = (PCell)nodeArrayList6.get(0);
        pstateNode6 = (PState)nodeArrayList7.get(0);
        {
            // Block
        LinkedList listNode7 = new LinkedList();
        listNode7 = (LinkedList)nodeArrayList8.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        {
            // Block
        LinkedList listNode9 = new LinkedList();
        listNode9 = (LinkedList)nodeArrayList9.get(0);
	if(listNode9 != null)
	{
	  listNode10.addAll(listNode9);
	}
        }

        pdescriptionNode1 = new ADescription(tidentifierNode2, tnamespaceNode3, pvertexNode4, pcellNode5, pstateNode6, listNode8, listNode10);
        }
	nodeList.add(pdescriptionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AAvertex1Vertex */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PVertex pvertexNode1;
        {
            // Block
        TFilename tfilenameNode2;
        LinkedList listNode3 = new LinkedList();
        tfilenameNode2 = (TFilename)nodeArrayList3.get(0);
        {
            // Block
        }

        pvertexNode1 = new AVertex(tfilenameNode2, listNode3);
        }
	nodeList.add(pvertexNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce AAvertex2Vertex */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PVertex pvertexNode1;
        {
            // Block
        TFilename tfilenameNode2;
        LinkedList listNode4 = new LinkedList();
        tfilenameNode2 = (TFilename)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pvertexNode1 = new AVertex(tfilenameNode2, listNode4);
        }
	nodeList.add(pvertexNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AState */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PState pstateNode1;
        {
            // Block
        TFilename tfilenameNode2;
        tfilenameNode2 = (TFilename)nodeArrayList3.get(0);

        pstateNode1 = new AState(tfilenameNode2);
        }
	nodeList.add(pstateNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce ACell */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCell pcellNode1;
        {
            // Block
        TFilename tfilenameNode2;
        tfilenameNode2 = (TFilename)nodeArrayList3.get(0);

        pcellNode1 = new ACell(tfilenameNode2);
        }
	nodeList.add(pcellNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce ASingleReadScalarOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadScalarOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AListReadScalarOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadScalarOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce ASingleReadVectorOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadVectorOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce AListReadVectorOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadVectorOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce ASingleReadTokenVectorTwoPowDOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadVectorTwoPowDOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce AListReadTokenVectorTwoPowDOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadVectorTwoPowDOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce ASingleReadStencilOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadStencilOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AListReadStencilOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AReadStencilOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce ASingleWriteScalarOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteScalarOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AListWriteScalarOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteScalarOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce ASingleWriteVectorTwoPowDOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteVectorTwoPowDOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce AListWriteVectorTwoPowDOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteVectorTwoPowDOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce ASingleWriteVectorOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteVectorOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AListWriteVectorOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteVectorOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce ASingleWriteStencilOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteStencilOperation(tidentifierNode2);
        }
	if(poperationNode1 != null)
	{
	  listNode3.add(poperationNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AListWriteStencilOperationList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        POperation poperationNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        poperationNode1 = new AWriteStencilOperation(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(poperationNode1 != null)
	{
	  listNode4.add(poperationNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce ASingleEventMappingList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PEventMapping peventmappingNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        peventmappingNode1 = new AEventMapping(tidentifierNode2);
        }
	if(peventmappingNode1 != null)
	{
	  listNode3.add(peventmappingNode1);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AListEventMappingList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        PEventMapping peventmappingNode1;
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);

        peventmappingNode1 = new AEventMapping(tidentifierNode2);
        }
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(peventmappingNode1 != null)
	{
	  listNode4.add(peventmappingNode1);
	}
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
	nodeList.add(listNode4);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce AAsingleadapterlist1AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode3, listNode4);
        }
	if(padapterNode1 != null)
	{
	  listNode5.add(padapterNode1);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AAsingleadapterlist2AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode6 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode4, listNode5);
        }
	if(padapterNode1 != null)
	{
	  listNode6.add(padapterNode1);
	}
        }
	nodeList.add(listNode6);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce AAsingleadapterlist3AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode6 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode3, listNode5);
        }
	if(padapterNode1 != null)
	{
	  listNode6.add(padapterNode1);
	}
        }
	nodeList.add(listNode6);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce AAsingleadapterlist4AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode7 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList5.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode4, listNode6);
        }
	if(padapterNode1 != null)
	{
	  listNode7.add(padapterNode1);
	}
        }
	nodeList.add(listNode7);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AAlistadapterlist1AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode6 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode4 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode3, listNode4);
        }
        listNode5 = (LinkedList)nodeArrayList4.get(0);
	if(padapterNode1 != null)
	{
	  listNode6.add(padapterNode1);
	}
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }
	nodeList.add(listNode6);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce AAlistadapterlist2AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode7 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        LinkedList listNode6 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode4, listNode5);
        }
        listNode6 = (LinkedList)nodeArrayList5.get(0);
	if(padapterNode1 != null)
	{
	  listNode7.add(padapterNode1);
	}
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
	nodeList.add(listNode7);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce AAlistadapterlist3AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode7 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        LinkedList listNode6 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode3 = new LinkedList();
        LinkedList listNode5 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode3, listNode5);
        }
        listNode6 = (LinkedList)nodeArrayList5.get(0);
	if(padapterNode1 != null)
	{
	  listNode7.add(padapterNode1);
	}
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
	nodeList.add(listNode7);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AAlistadapterlist4AdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode8 = new LinkedList();
        {
            // Block
        PAdapter padapterNode1;
        LinkedList listNode7 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidentifierNode2 = (TIdentifier)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList5.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        padapterNode1 = new AAdapter(tidentifierNode2, listNode4, listNode6);
        }
        listNode7 = (LinkedList)nodeArrayList6.get(0);
	if(padapterNode1 != null)
	{
	  listNode8.add(padapterNode1);
	}
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
	nodeList.add(listNode8);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce ASingleMergeWithUserDefinedAdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode1;
        tidentifierNode1 = (TIdentifier)nodeArrayList2.get(0);
	if(tidentifierNode1 != null)
	{
	  listNode2.add(tidentifierNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce AListMergeWithUserDefinedAdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode1;
        LinkedList listNode2 = new LinkedList();
        tidentifierNode1 = (TIdentifier)nodeArrayList2.get(0);
        listNode2 = (LinkedList)nodeArrayList3.get(0);
	if(tidentifierNode1 != null)
	{
	  listNode3.add(tidentifierNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce ASingleMergeWithPredefinedAdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode1;
        tidentifierNode1 = (TIdentifier)nodeArrayList2.get(0);
	if(tidentifierNode1 != null)
	{
	  listNode2.add(tidentifierNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce AListMergeWithPredefinedAdapterList */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        TIdentifier tidentifierNode1;
        LinkedList listNode2 = new LinkedList();
        tidentifierNode1 = (TIdentifier)nodeArrayList2.get(0);
        listNode2 = (LinkedList)nodeArrayList3.get(0);
	if(tidentifierNode1 != null)
	{
	  listNode3.add(tidentifierNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {3, SHIFT, 1}, },
			{{-1, ERROR, 1}, {17, SHIFT, 3}, },
			{{-1, ERROR, 2}, {20, ACCEPT, -1}, },
			{{-1, ERROR, 3}, {4, SHIFT, 4}, },
			{{-1, ERROR, 4}, {19, SHIFT, 5}, },
			{{-1, ERROR, 5}, {0, SHIFT, 6}, },
			{{-1, ERROR, 6}, {12, SHIFT, 8}, },
			{{-1, ERROR, 7}, {1, SHIFT, 9}, },
			{{-1, ERROR, 8}, {18, SHIFT, 11}, },
			{{-1, ERROR, 9}, {12, SHIFT, 12}, },
			{{-1, ERROR, 10}, {2, SHIFT, 13}, },
			{{-1, REDUCE, 4}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, ERROR, 12}, {18, SHIFT, 18}, },
			{{-1, ERROR, 13}, {12, SHIFT, 19}, },
			{{-1, REDUCE, 0}, {13, SHIFT, 20}, {14, SHIFT, 21}, },
			{{-1, ERROR, 15}, {7, SHIFT, 24}, {8, SHIFT, 25}, {9, SHIFT, 26}, {10, SHIFT, 27}, },
			{{-1, ERROR, 16}, {7, SHIFT, 28}, {8, SHIFT, 29}, {9, SHIFT, 30}, {10, SHIFT, 31}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 19}, {18, SHIFT, 32}, },
			{{-1, ERROR, 20}, {11, SHIFT, 33}, },
			{{-1, ERROR, 21}, {11, SHIFT, 34}, },
			{{-1, REDUCE, 1}, {14, SHIFT, 21}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 24}, {17, SHIFT, 36}, },
			{{-1, ERROR, 25}, {17, SHIFT, 37}, },
			{{-1, ERROR, 26}, {17, SHIFT, 38}, },
			{{-1, ERROR, 27}, {17, SHIFT, 39}, },
			{{-1, ERROR, 28}, {17, SHIFT, 40}, },
			{{-1, ERROR, 29}, {17, SHIFT, 41}, },
			{{-1, ERROR, 30}, {17, SHIFT, 42}, },
			{{-1, ERROR, 31}, {17, SHIFT, 43}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 33}, {17, SHIFT, 44}, },
			{{-1, ERROR, 34}, {17, SHIFT, 45}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 8}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 10}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 12}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 14}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 16}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 20}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 18}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 22}, {5, SHIFT, 15}, {6, SHIFT, 16}, },
			{{-1, REDUCE, 24}, {13, SHIFT, 20}, },
			{{-1, REDUCE, 26}, {14, SHIFT, 21}, {15, SHIFT, 55}, {16, SHIFT, 56}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 55}, {17, SHIFT, 60}, },
			{{-1, ERROR, 56}, {17, SHIFT, 61}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 27}, {14, SHIFT, 21}, {16, SHIFT, 56}, },
			{{-1, REDUCE, 28}, {14, SHIFT, 21}, },
			{{-1, REDUCE, 34}, {15, SHIFT, 55}, },
			{{-1, REDUCE, 36}, {16, SHIFT, 56}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 29}, {14, SHIFT, 21}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 33}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 7}, },
			{{-1, 14}, },
			{{-1, 10}, },
			{{-1, 17}, {36, 46}, {37, 47}, {38, 48}, {39, 49}, {40, 50}, {41, 51}, {42, 52}, {43, 53}, },
			{{-1, 22}, {44, 54}, },
			{{-1, 23}, {22, 35}, {45, 57}, {58, 62}, {59, 64}, {63, 67}, },
			{{-1, 58}, {60, 65}, },
			{{-1, 59}, {58, 63}, {61, 66}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'component:'",
			"expecting: identifier",
			"expecting: EOF",
			"expecting: 'namespace:'",
			"expecting: namespace",
			"expecting: 'vertex:'",
			"expecting: 'dastgen-file:'",
			"expecting: 'cell:'",
			"expecting: filename",
			"expecting: 'state:'",
			"expecting: 'cell:', 'read', 'write'",
			"expecting: 'event-mapping:', 'adapter:', EOF",
			"expecting: 'scalar:', 'vector:', 'vector2PowD:', 'stencil:'",
			"expecting: 'name:'",
			"expecting: 'adapter:', EOF",
			"expecting: 'adapter:', 'merge-with-user-defined-mapping:', 'merge-with-predefined-mapping:', EOF",
			"expecting: 'adapter:', 'merge-with-predefined-mapping:', EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 5, 6, 7, 8, 6, 9, 10, 8, 6, 11, 12, 12, 7, 9, 8, 13, 13, 14, 2, 1, 1, 1, 1, 1, 1, 1, 1, 11, 1, 1, 2, 10, 10, 10, 10, 10, 10, 10, 10, 11, 15, 7, 7, 7, 7, 7, 7, 7, 7, 14, 1, 1, 2, 16, 14, 15, 16, 2, 14, 2, 16, 14, 2, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
