/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.peano.pdt.node;

import org.peano.pdt.analysis.*;

@SuppressWarnings("nls")
public final class TTokenVectorFivePowD extends Token
{
    public TTokenVectorFivePowD()
    {
        super.setText("intergrid-operator:");
    }

    public TTokenVectorFivePowD(int line, int pos)
    {
        super.setText("intergrid-operator:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokenVectorFivePowD(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokenVectorFivePowD(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokenVectorFivePowD text.");
    }
}
